baseURL = 'https://axdxrxi.github.io/mynews/'
languageCode = 'fr-fr'
title = 'My News of the Day'
theme = 'ananke'
enableRobotsTXT = true
publishDir = 'public'

[params]
  # Optionnel : message d'accueil sur la page d'accueil
  description = "Articles générés automatiquement chaque jour avec Mistral AI."

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.goldmark.parser]
    autoHeadingID = true

  [markup.goldmark.extensions]
    typographer = true
    table = true
    linkify = true
